### ISSUE TITLE
Refactor Docker files

### ISSUE THREAD

**Issue by zit-hb** [zecure/packaging#1]
The Dockerfiles are in need for some refactoring:

* use modern systems and libs
* use vanilla postgresql and create database layout with ui
* add docker-compose config for easier use
* add env variables to configure passwords etc.
* remove shadowd_custom

**Comment by rips-hb** [comment]
Done. Only exception is that the database is already initialized with the base layout. Updates will have to be done through migrations in the ui.

**Comment by zit-hb** [comment]
Done. Only exception is that the database is already initialized with the base layout. Updates will have to be done through migrations in the ui.
